### ISSUE TITLE
Can’t access server’s GUI. NGINX bad gateway error 

### ISSUE THREAD

**Issue by CTAA56** [thinkst/canarytokens-docker#101]
Hello,
I have the server built on a Ubuntu 20 cloud instance. I have actually built this server multiple times earlier this year but didn’t have this issue. I know the source code is continuously updated so something must’ve changed.

when running the server, I am unable to access the GUI with its public IP address (I haven’t setup the domain for it yet). I get a HTTP 502 error from NGINX
On the back end I get a “failed (113: No route to host) while connecting to upstream, client: , server: , request: "GET /generate HTTP/1.1", upstream: "http://172.18.0.3:8082/generate", host: (public IP address)

The only changes I made for my frontend.env
Is 
CANARY_DOMAINS=(Public IP)
CANARY_PUBLIC_IP=(Public IP)

Changes in the switchboard.env
CANARY_PUBLIC_IP=(Public IP)
CANARY_PUBLIC_DOMAIN-(Public IP)

I haven’t made any additional configurations yet because I want to confirm the server can run.

Additionally, I keep receiving the python2 deprecation warning even though I made sure to install python3 for this setup. I confirmed python 2 is not installed on the server, however I get the warning from both frontend and switchboard containers:

usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationwarning: Python 2 is no longer supported by the Python core team…”

Does the code reference Python 2 anywhere? I didn’t see it anywhere but maybe I’m not looking thoroughly. I am also not sure if that’s why I can’t access the server’s GUI.

**Comment by jayjb** [comment]
Hi @CTAA56,

Thanks for writing in and sorry you having an issue. 

Just to answer your python2 vs python3 question:
> Does the code reference Python 2 anywhere? I didn’t see it anywhere but maybe I’m not looking thoroughly. I am also not sure if that’s why I can’t access the server’s GUI.
The canarytokens server runs on python2 but that is contained within the container environment. So i wouldn't expect you to need python2 running on your server, but since it is deprecated, you will still see warnings in the output from within the docker container.

> On the back end I get a “failed (113: No route to host) while connecting to upstream, client: , server: , request: "GET /generate HTTP/1.1", upstream: "http://172.18.0.3:8082/generate", host: (public IP address)
So this error usually means that the container that it is expecting to send the data, in this case our frontend container, is having issues. When you run `docker-compose up`, can you confirm that the all the containers start up successfully? There is four: `switchboard`, `frontend`, `redis`, `nginx`.

**Comment by jayjb** [comment]
hi @CTAA56<

Just checking that you added `WG_PRIVATE_KEY_SEED`? It is a new required value and the instructions show a quick easy way to generate one.

**Comment by CTAA56** [comment]
Thank you for your quick response!
The issue was that I missed the updated required value.

I was using the instructions I created for myself previously.

It is now working as intended.
