### ISSUE TITLE
Random Domains used in DNS-Token

### ISSUE THREAD

**Issue by gearanach** [thinkst/canarytokens-docker#141]
Hello,

when trying to generate a DNS-token I get 2 different types of tokens: 1 with the (correct) structure <Token>.dl.<my domain>.de and 1 with the wrong structure <Token>.<my domain>.de. The correct one gets generated about 2/3 times.
I've tried setting the project up again from scratch (I even reinstalled Ubuntu on the server) but it doesn't work. In my frontend.env, I have the CANARY_DOMAINS value set to the .dl-domain and in the switchboard.env, I have the CANARY_PUBLIC_DOMAIN set to the same value. However, that doesn't fix the problem. 

Kind Regards

**Comment by jayjb** [comment]
Hi @gearanach,

Thanks for checking in! Lets see if we can get to the bottom of this. 

I don't think I am understanding what the different DNS tokens structures you are getting means? i.e. 
>2 different types of tokens: 1 with the (correct) structure .dl..de and 1 with the wrong structure ..de. The correct one gets generated about 2/3 times.
What does `.dl..de` vs `..de` mean? Can you give me another example? Or try explain further?

**Comment by gearanach** [comment]
Hi @jayjb 

thanks for the response.
What I mean is that I get tokens generated with two different domains. One being like this:
<Token>.dl.mydomain.de
and another one looking like this:
<Token>.mydomain.de
Tokens that get generated to use the .dl.mydomain.de-Domain work. Tokens that do not use the .dl-subdomain don't.

Any ideas?

**Comment by jayjb** [comment]
Hi @gearanach,

Thanks for the explanation. Can i just confirm a few things:
- When you getting different domains, is it the same token type?

- When you say it doesn't work, can you confirm where the break is? 
To do this we could check in the docker whether the DNS request is making it to the docker switchboard. You could do this by running the docker container in the foreground (without `-d`) and confirming whether looking up the token domain works.
```
dig TOKEN.dl.domain.de
dig TOKEN.domain.de
```
You should see logs showing those requests coming through. If not, we know that it is failing because our DNS isn't setup correctly. If it is making it through, we would need to debug why the server isn't creating an alert.

- Getting tokens generated with two different domains is certainly strange (if you are creating the same token type). I would expect a single domain. We can check whether we have multiple domains in the database too. On the box running your canarytokens docker:
```
$ docker exec -ti redis /bin/bash
$ redis-cli smembers 'canary_domains'
```

**Comment by gearanach** [comment]
Hi @jayjb 

Ok so the output for the redis-command is definitely strange...
When running the commands, I get this output:
```bash
1) "dl.anothertestforcanaries.de"
2) "dl.aothertestforcanaries.de"
3) "anothertestforcanaries.de"
```
I can't see why this happens. None of the configuration-files switchboard.env, frontend.env or certbot.env contain domains 2 and 3. I have run (multiple) 
```bash
sudo docker stop $(docker ps -q)
sudo docker system prune -a
```
at this point. Any idea how this can happen?

**Comment by gearanach** [comment]
Also yes, it is the same token-type

**Comment by jayjb** [comment]
Hi @gearanach,

So whats happening there our docker-compose file is setting up multiple services (see `docker-compose.yml`). Inside you will notice:
```
services:
  redis:
    restart: always
    image: redis
    volumes:
    - ./data:/data/
    container_name: redis
    command: redis-server --appendonly yes --protected-mode no --save 60 1
```
And what that is doing is running a redis container but, for persistence so that you dont lose everything between docker container restarts, we map a redis db that is stored locally into the docker container. 

So when you `docker-compose up` with `CANARY_DOMAINS=bob.domain.here` then restart but change the `CANARY_DOMAINS=actually.not.bob.here`; it stores both of those domains in your redis file. There are some reasons for this, but it is not obvious that it is happening. 

You can either remove the file in the `data` folder, to start clean; or you can go into the redis container again and remove them manually.

**Comment by gearanach** [comment]
Hi @jayjb,

thanks, I will do that and report back.

**Comment by gearanach** [comment]
Hi @jayjb,

yes, the solution worked. Thank you for your help, I wouldn't have figured this out.
