### ISSUE TITLE
Issues with Geo Location

### ISSUE THREAD

**Issue by Manu-Surendra** [thinkst/canarytokens-docker#17]
After i click on the manage tokens, the geolocation for the docker image does not seem to be working. What am i missing here

**Comment by mamisano** [comment]
I have fixed the issue in a fork of the application and I am waiting for @thinkst to approve the pull request.
In the mean time, the fix is very easy.

1. Create a free Google Maps Javascript API key (https://console.developers.google.com)
2. Add the following to the frontend.env configuration file:
   CANARY_GOOGLE_API_KEY=_your_api_key_

Please let me know if that works.

**Comment by Manu-Surendra** [comment]
hey thanks a lot. I tested it and it works perfectly fine. Keep up the good work Mamisano

**Comment by thinkst** [comment]
Thanks @mamisano for the pull request! We really hope everyone is enjoying the tokens as much as we are
