### ISSUE TITLE
[BUG] Nginx incorrect routing to nest paths

### ISSUE THREAD

**Issue by brma2805** [thinkst/canarytokens-docker#178]
**Describe the bug**
A problem with nginx routing is causing the routes attended to the frontend to be directed to the backend. The backend returns a 1*1 image, preventing the webpage to be loaded properly, in other words it returns the output of this function render_GET function

**To Reproduce**
1. Spin up the canarytokens as descibred in the docs here https://github.com/thinkst/canarytokens-docker 
2. Run `Docker compose up`
3. Try to access the default home page your-hosted-canary[.]domain/
4. Returns a blank page with no html content. 
5. Open dev tools and look at the network request
6.  CSS and JS files are returned as image/gif type

**Expected behavior**
Expected to load the default canarytoken as seen here https://canarytokens.org/nest/ , but blank page is loaded instead with only the contents from the index.html file

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 126.0.0.0

**Solution**
Running the command below solves the problem. I believe perhaps this image must be rebuildt and updated `thinkst/canarytokens_nginx`
 - `Docker compose up --build`

Thanks for sharing this awesome opensource project 💯

**Comment by jayjb** [comment]
Hi @brma2805,

Sorry for the delay in getting back to you. Would you mind sharing your config with us? The different `.env` files. 

The reason I ask is because the canarytokens server will serve different pages for different domains. You will notice with the production server (`canarytokens.org`); it is `canarytokens.org` that serves the webpage we interact with, while canarytokens actually use the `canarytokens.com` domain - if you navigate to that, you will get a different page.
