### ISSUE TITLE
The canaraytokens page is displayed in blank

### ISSUE THREAD

**Issue by codigoartesano** [thinkst/canarytokens-docker#188]
**Describe the bug**
I'm install canarytoken, accourding your instructions , but the page is in blank and if the source code is: 

<body>
  <div id="app"></div>
</body

**To Reproduce**
1. execute: docker compose up

I'm using Ubuntu 22
New VPS
and no more docker images or instances.

**Comment by illegalMercy** [comment]
I had the same problem. It was solved by adding 
```
types {
    application/javascript js; text/css css;
}
```
to `/nginx/nginx.conf` and rebuilding the image

**Comment by thinkst-nick** [comment]
Hi @codigoartesano,

I noticed that the `thinkst/canarytokens_nginx` docker image hadn't been rebuilt since our move to Vue and the subsequent routing changes. This meant that the image had an old `nginx.conf` that did not handle the `/nest/*` routes correctly.

I've pushed a new image, could you please try `docker pull thinkst/canarytokens_nginx:latest` and then `docker compose up` again to see if it has solved your issue?

Thanks
Nick

**Comment by codigoartesano** [comment]
It's working now!... thank you

**Comment by thinkst-nick** [comment]
It's a pleasure, I'm glad it's sorted (sorry about the trouble caused).

Happy tokening :)
