### ISSUE TITLE
PDF canaries will not fly / token integration

### ISSUE THREAD

**Issue by residentialflipper** [thinkst/canarytokens-docker#19]
I've installed the docker and server is working fine. But I run into a couple of issues.

I added a second domain for PDF in NXDOMAINS but tokens won't fire. The link tries to open but response is No such resource / No such child resource and the token isn't triggered. The URL in the pdf tokenid.mydomain.com/zzzz without the post-fix /zzzzz now allows access to the (tokenid)subdomain after changes to my DNS, so tokenid.mydomain.com/ accesses tokenid.mydomain.com/#generate. The complete link itself won't work however, so somehow the /zzzzz post-fix does not register when created. A Word token URL will trigger the token and a PDF token from canary tokens.org will also trigger even if it has the same structure as my token and gives the same failure if extracted and used as a direct URL. Do I need to change anything in my DNS in order for the NXDOMAINS pdf-token domain can fire besides changing fronted.env?

Last point: any suggestions / experience on how to quickly integrate a generated token into an existing Word / PDF once I get my tokens working?

**Comment by x011** [comment]
The pdf tokens also don't work on my docker . Have you had any luck with this?

**Comment by thinkst** [comment]
Hey @residentialflipper, 

Sorry for the delay. I just wanted to quickly check if you got it working? 

With regards to changes to your DNS, the domain for the NXDomain that you supplied should also point to your Canarytokens public IP (the same as your regular Domain that you supplied in frontend.env).

Please let me know if you got this working or if I can dig further to help (and ill check up on an answer for your Last point question)

**Comment by nielsduelund** [comment]
I too have problems with tokens in PDF-files (Word and URL are working fine).
When I open the PDF I'm prompted to allow access to the site - this is not good for stealth :-/
If I allow the access, a browser is opened for the URL (also not good for stealth) where I get "Oh dear, an error occured! 404: No Such Resource".
I'm running the Docker image in an environment where I use hosts-file instead of proper DNS, but name resolution should be the same I guess ... ?

**Comment by thinkst** [comment]
Hey @nielsduelund,

Thanks for getting in touch. Would you mind letting me know how you are opening the PDFs? We have specified that it is an Adobe PDF token, because we know how it works there, although it may work on other PDF viewers too, we can't guarantee that.

If you navigate to the URL embedded in the PDF, you will get an error because that url is a DNS token, which means that the server handling the requests will not serve up any HTTP response (i.e. the resolution of the DNS name is the token, not a GET request).

**Comment by nielsduelund** [comment]
Sorry for not comming back on this.
I realized that many things were wrong in my setup, so who knows what is really wrong :-/
I'll be back when my setup is working (but I have to open another issue for this to happen).

**Comment by thinkst** [comment]
Closing this issue for now. Please open a new issue if this issue comes up again.
