### ISSUE TITLE
Letsencrypt method doesn't work reliably

### ISSUE THREAD

**Issue by kuriackovskij** [thinkst/canarytokens-docker#36]
Hi.
I found one annoying issue...Especially after enabling basic_auth in Nginx.
Letsencrypt has a limit of cert generations for the same domain which is 5/week.
Now here is the situation I met - each time when starting server with docker-composer-letsencrypt.yml it is requesting new certificate from Letsencrypt provider. After several CanaryTokens server/container restart attempts my https stopped working (server refuses connection), while http is working fine... I ran container manually in foreground mode and noticed from the log it's failing to register with letsencrypt service which returns "Too many attempts" error. I tried to "hack" it by replacing nginx.conf under /nginx/ directory to the the one under /certbot-nginx/ directory and added port 443 in docker-composer.yml file, then rebuild container to apply changes (all that was done with the hope to skip letsencrypt cert request part) - but that trick didn't work... 
I think if there would be an additional configurable option/parameter implemented which would tell "Use letsencript to obtain new cert OR Don't use letsencrypt" while running https setup that would be the easiest solution because would allow to run HTTPS without re-requesting cert each time. I hope that can be added.
For now I am stuck for 1 week with http and basic authentication which sends my credentials in plain-text (actually base64 encoded, but that's mickey mouse) with every request I do to CT :(

**Comment by thinkst** [comment]
Hey @kuriackovskij,

Sorry that you found this issue out the hard way. We do mention that there is a rate limit for the lets encrypt (but we dont mention what it is, ill update the docs, thanks!).

We haven't added the fix we use for our actual canarytokens server yet; mostly because it is quite hacky and we are trying to refine it. Ill bump this up the priority list though because I know it can be quite an irritation. 

The idea we had is to store the cert once certbot has received it (store it on some storage that you map to inside the nginx docker so that once the docker container is destroyed, the cert is still kept). Then when you restart the docker instances, that container should first check if the cert exists before requesting a new one. 

If you solve this issue, we would be super happy with a PR 😜

**Comment by ch40s** [comment]
+1 for a proper solution with certbot. Certbot-auto is currently failing and can't be used at all, the latest version of certbot is required. Storing the obtained certificate in a persistent volume would make sense.

**Comment by ch40s** [comment]
@kuriackovskij check this out: https://github.com/thinkst/canarytokens-docker/issues/73
I was able to do that by using the same certificate and not requesting one each time.
