### ISSUE TITLE
Getting different IP in pdf  Alert

### ISSUE THREAD

**Issue by prashantvidja** [thinkst/canarytokens-docker#41]
Hello,

When i am generating alert using PDF token it is showing different IP then my ISP public ip.
It is showing ip of the dns server that's the ISP is using to resolve the address.
In most cases, it is different from the location of the user who is actually opening the file.
And in some tokens I am getting same as ISP IP. so it is not showing the exact location it is false positive in many cases.
Is there any different method are you using for generating alert for PDF token?

Thanks

**Comment by thinkst** [comment]
Hey @prashantvidja,

You are totally correct and what you are seeing is expect. The PDF token using a DNS token as its base. This means that it will be able to get out of more restrictive networks (since HTTP is often blocked), but it will only display the DNS server ip.

Please let me know if this explains it, otherwise we can discuss it more.

**Comment by prashantvidja** [comment]
@thinkst 
Thanks you. I got it.
You are doing great job!
