### ISSUE TITLE
aws warning about an open recursive DNS resolver

### ISSUE THREAD

**Issue by psifertex** [thinkst/canarytokens-docker#51]
I setup a canarytokens-docker instance some time ago though I haven't done much with it and I just recently got an alert from AWS that it's been flagged by an abuse report as running an open-resolver.

It's possible that this is due to how /I/ configured the setup and not necessarily the fault of the image itself, but I figured I'd file it here just in case. The server wasn't important so I just killed the instance for now.

**Comment by jayjb** [comment]
Hi @psifertex,

Thanks for reporting this; Ill take a look and see what needs to be done.

**Comment by jayjb** [comment]
Hi @psifertex,

I did some digging and asking around. The AWS mail for this is a false positive. Basically, the Canarytokens DNS is an open DNS server but not recursive. AWS detects it as recursive because it doesn't reply with NX domains but rather an IP address. But the IP address it replies with is its own, always. So it doesn't reach out to other DNS servers to find an answer - like a proper recursive DNS server. 

Hope this explains it.

**Comment by psifertex** [comment]
Yup, I realize they were wrong. I pushed back on them several times to try to get them to understand why a canary is not a really open resolver as it's not recursively querying but they seemed... slow to understand.
