### ISSUE TITLE
Security concerns?

### ISSUE THREAD

**Issue by encryptblockr** [thinkst/canarytokens-docker#62]
This is supposed to be a security tool but yet the architecture is a bit flawed in terms of security.
Why is the generate endpoint for example exposed to the internet?

Shouldn't that be restricted in a way where certain kind of access is needed to be able to generate tokens? or am i just over thinking things?

basic auth is not enough for this, again the security concerns are kind of ignored and taking a seat back which is not a good approach

**Comment by jayjb** [comment]
Hi @encryptblockr,
Sorry for the delayed response. My comments are inline:

> This is supposed to be a security tool but yet the architecture is a bit flawed in terms of security.
Those are fighting words! (In seriousness, its worth discussing).

> Why is the generate endpoint for example exposed to the internet?
The answer to this one is simple. We host it so that people on the Internet can use it. It is a requirement therefore that the endpoint exist on the Internet.

> Shouldn’t that be restricted in a way where certain kind of access is needed to be able to generate 
> tokens?
Maybe?

> or am i just over thinking things?
I suspect it might just be a misunderstanding

> basic auth is not enough for this,
This is a good place to start. You say that “basic auth is not enough for this”.
What do you mean by “this?”

A super important rule, when attempting to secure something, is to understand how it will be abused. To generate a “threat model” for the service.

In this case, we need to figure out: “What can an attacker do if they get access to this interface without logging in?”

For example: if i can access your inbox without logging in, i can read your mail; i can send mail as you; etc. If i can access your corporate AD account without logging in, i can do a bunch of things.

So the question is: If i can generate tokens without logging in, what can i do?
We’ve thought pretty long and hard about this, and the best we can come up with is, we can generate tokens. This is kinda the point of the service (to allow people to generate tokens) so we think thats ok. We’d love to hear if you can think of actual negatives here?

> again the security concerns are kind of ignored and taking a seat back which is not a good approach
Security isn’t being ignored here, and isn’t taking a “seat back” - it’s taking an appropriate seat. I.e. one of the big problems in security, is usability. If you make things too painful to use, people won’t use it - and then, if it was a useful service, everyone loses. Instead, in this case, when there is no downside to exposing the service, it turns out that exposing the service decreases friction to its usage, which results in a nett win.

Please let us know if you have any other thoughts on this.

PS: You can download docker images of the service to run on your own infrastructure. The basic auth documentation, added to that [here](https://github.com/thinkst/canarytokens-docker#enabling-basic-auth-to-your-canarytokens-site) essentially gives you a guide for how you can separate the “admin/generate” components from the actual service, so if you were running a private instance, you can take care of this easily.
	
Thanks again for reaching out.

**Comment by fishertwelve** [comment]
I know this topic is closed but I also had a question around security. What is the endpoint that tokens are reporting back to? If it was /beacon for example, couldn't an approach to the exposed service "problem" be to whitelist internet traffic to only to example.com/beacon or even blacklisting internet traffic to /generate, /history, etc. ?

Something like...
`location ~* (/generate|/manage|/download|/history|/settings|/resources).* {`
    `allow 10.0.0.0/8;`
    `deny all;`
`}`
