### ISSUE TITLE
Basic authentication 

### ISSUE THREAD

**Issue by mrrobotnl** [thinkst/canarytokens-docker#95]
I have a question I am currently trying to install the basic authentication. But doesn’t seem to get it working I get a Nginx 404 or 403 error. I created the .htpasswd file with a local user. 

I am trying to configure this in a container environment (docker) but my question is? Under the instructions you point at /etc/nginx/.htpasswd. But this cannot be the case because I try to configure this with docker. Do I need to install Nginx as well?

**Comment by jayjb** [comment]
Hi @mrrobotnl,

Our Canarytokens docker compose file will automatically create a Nginx container (as well as 3 others). In those instructions, advise adding that file to the place where the custom Nginx image is created. Can you maybe tell me exactly the steps are have taken? With directory listing so that we can figure this out quickly

**Comment by mrrobotnl** [comment]
Hey Jayjb, Thanks for responding that quickly. I have already solved it. Silly me had not past the COPY line in the docker. That's why it not worked. But anyway thanks for helping
