### ISSUE TITLE
Change the main page 

### ISSUE THREAD

**Issue by mrrobotnl** [thinkst/canarytokens-docker#99]
Hey developers is it perhaps possible that I can view the main html page and possible edit this in mine own project?  I want to try another layout, perhaps an other font or positioning to the left instead of dead center. 

Is this possible, and so yes where can I find the main .html and .css file?

**Comment by jayjb** [comment]
Hi @mrrobotnl,

You can totally customise the page to be your own. There would be some extra steps required though. 
1. You would need to make the changes to code in the [here](https://github.com/thinkst/canarytokens) which is the code that this `canarytokens-docker` runs. 
2. You would then need to build a new image with your new code changes (or UI changes)
3. You can then use the docker compose to run your images. You would need to alter the `docker-compose.yml` files slightly, to run your new images rather than grabbing ours.

Let me know if this a path you would like to take.

**Comment by mrrobotnl** [comment]
> 

Hey Jayjb, thanks for the quick response. I going to give this a try. Thank you very much

**Comment by mrrobotnl** [comment]
And what file should I edit for UI changes is that the httpd_site.py? And is there perhaps a simple guide?
